### ISSUE TITLE
Support For Moonbeam1

### ISSUE THREAD

**Issue by Vigilence** [DEVAIEXP/image-interrogator#10]
**Is your feature request related to a problem? Please describe.**
Just discovered this software and love what is available so far!  I would love to see moonbeam1 added in the future.

https://huggingface.co/vikhyatk/moondream1

**Describe the solution you'd like**
Moonbeam1 added as a model

**Comment by elismasilva** [comment]
I appreciate that you liked it, we can add this model, I'm also looking at other models that can be added. When I have time available I will be able to work on these improvements.

**Comment by elismasilva** [comment]
Added support in release v1.0.1
