### ISSUE TITLE
Keep model in ram until I press unload button or switch models

### ISSUE THREAD

**Issue by Vigilence** [DEVAIEXP/image-interrogator#11]
**Is your feature request related to a problem? Please describe.**
I did some testing of single image and noticed that the cogvlm model unloads after it does a caption.  Is there any chance we can get a setting that keeps the model in the ram until we switch models or unload it via a button?

**Describe the solution you'd like**
Keep model in ram until I press unload button or switch models

**Comment by elismasilva** [comment]
I will check if it is possible to make this adjustment for a next version. Thank you!

**Comment by Vigilence** [comment]
Thank you so much!

**Comment by elismasilva** [comment]
Fixed in release v1.0.1
