### ISSUE TITLE
help, pls

### ISSUE THREAD

**Issue by xlibfly** [DEVAIEXP/image-interrogator#21]
Batch process started.
Preparing images from folder...
Running with this settings...
----------------------------------------------------------------------------------------------------
Precision Type: FP16
Load Mode: 16bit
Device: auto
Optimize for Low VRAM: False
Include image features in the prompt: True
Don't save dataset images: False
Generate individual caption file: True
Generate dataset: True
Dataset Name: Default
Caption Model: llava-v1.5-7b
Max outputs tokens: 2048
Temperature: 0.2
Top p: 0.7
CLIP Model: ViT-L-14/openai
Feature Mode: classic
Question prompt: Provide caption for the image in one sentence. Be detailed but precise.
----------------------------------------------------------------------------------------------------
Something went wrong while process captions.
Traceback (most recent call last):
  File "D:\SDfile\image-interrogator\image-interrogator.py", line 508, in batch_process
    validate_reload(caption_model_name, clip_model_name, check_lowvram, device, generate_features, _precision_type, load_4bit, load_8bit)
  File "D:\SDfile\image-interrogator\image-interrogator.py", line 310, in validate_reload
    load_ci()
  File "D:\SDfile\image-interrogator\image-interrogator.py", line 59, in load_ci
    if ci:
NameError: name 'ci' is not defined

**Comment by elismasilva** [comment]
can you try do a fresh install, ive merged some fixes on branch master. let me know if it solved. do git pull command to update your code.
